name: Build and push
on:
  workflow_run: 
    workflows: ["CI"]
    types: 
      - completed
    branches: 
      - main

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: short-hash
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
                ghcr.io/two-small-onions/bff:latest
                ghcr.io/two-small-onions/bff:${{ steps.short-hash.outputs.SHA_SHORT }}
