name: CI
on:
    push:
        branches:
            - main
    pull_request:
    
jobs:
    ci:
        name: Run CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: rustup update
            - run: cargo check